services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8001:80"
        volumes:
            -  ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/laravel
        depends_on:
            - php
            - postgres

    php:
        build:
            context: docker/dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel

    postgres:
        image: postgres:16
        ports:
            - "5442:5432"
        volumes:
            - "./db_data:/var/lib/postgresql/data"
        env_file:
            - docker/postgres/postgres.env
    
    composer:
        build: 
            context: docker/dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - "./src:/var/www/laravel"

    artisan:
        build:
            context: docker/dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - "./src:/var/www/laravel"
        entrypoint: ["php", "/var/www/laravel/artisan"]
